version: "3"
services:

  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=a1b2c3d4
    ports:
      - 5432:5432

  auth-api:
    build: ./auth-api
    container_name: auth-api
    environment:
      - PORT=8080
      - DB_HOST=auth-db
    ports:
      - 8080:8080
    depends_on:
      - auth-db

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=a1b2c3d4
    ports:
      - 5433:5432

  product-api:
    build: ./product-api
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    ports:
      - 27017:27017

  sales-api:
    build: ./sales-api
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
